spring:
  mvc:
    view:
      suffix: html
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/itcentercrm
    username: itcenter
    password: wtmlopuhfgfdaz1


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size:
        20MB